// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/features/weather/domain/usecases/get_weather_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/src/features/weather/domain/entities/forecast.dart'
    as _i3;
import 'package:weather_app/src/features/weather/domain/entities/location.dart'
    as _i6;
import 'package:weather_app/src/features/weather/domain/entities/weather.dart'
    as _i2;
import 'package:weather_app/src/features/weather/domain/repositories/weather_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeather_0 extends _i1.SmartFake implements _i2.Weather {
  _FakeWeather_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForecast_1 extends _i1.SmartFake implements _i3.Forecast {
  _FakeForecast_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i4.WeatherRepository {
  @override
  _i5.Future<_i2.Weather> getWeather(_i6.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#getWeather, [location]),
            returnValue: _i5.Future<_i2.Weather>.value(
              _FakeWeather_0(this, Invocation.method(#getWeather, [location])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Weather>.value(
              _FakeWeather_0(this, Invocation.method(#getWeather, [location])),
            ),
          )
          as _i5.Future<_i2.Weather>);

  @override
  _i5.Future<_i3.Forecast> getForecast(_i6.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#getForecast, [location]),
            returnValue: _i5.Future<_i3.Forecast>.value(
              _FakeForecast_1(
                this,
                Invocation.method(#getForecast, [location]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Forecast>.value(
              _FakeForecast_1(
                this,
                Invocation.method(#getForecast, [location]),
              ),
            ),
          )
          as _i5.Future<_i3.Forecast>);
}
