// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/features/weather/data/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/src/features/weather/data/datasources/weather_remote_datasource.dart'
    as _i5;
import 'package:weather_app/src/features/weather/data/models/forecast_model.dart'
    as _i4;
import 'package:weather_app/src/features/weather/data/models/weather_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeatherModel_1 extends _i1.SmartFake implements _i3.WeatherModel {
  _FakeWeatherModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForecastModel_2 extends _i1.SmartFake implements _i4.ForecastModel {
  _FakeForecastModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i5.WeatherRemoteDataSource {
  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.Client);

  @override
  _i6.Future<_i3.WeatherModel> fetchWeather(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWeather, [latitude, longitude]),
            returnValue: _i6.Future<_i3.WeatherModel>.value(
              _FakeWeatherModel_1(
                this,
                Invocation.method(#fetchWeather, [latitude, longitude]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.WeatherModel>.value(
              _FakeWeatherModel_1(
                this,
                Invocation.method(#fetchWeather, [latitude, longitude]),
              ),
            ),
          )
          as _i6.Future<_i3.WeatherModel>);

  @override
  _i6.Future<_i4.ForecastModel> fetchForecast(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForecast, [latitude, longitude]),
            returnValue: _i6.Future<_i4.ForecastModel>.value(
              _FakeForecastModel_2(
                this,
                Invocation.method(#fetchForecast, [latitude, longitude]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.ForecastModel>.value(
              _FakeForecastModel_2(
                this,
                Invocation.method(#fetchForecast, [latitude, longitude]),
              ),
            ),
          )
          as _i6.Future<_i4.ForecastModel>);
}
